# Generated by Django 4.0.6 on 2023-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
